main.out:

	g++ node.h linearStructure.h main.C  RemoveException.h -o main.out
	
	./main.out


run:

	./main.out



clean:

	rm -f main.out



zip:

	tar -cvz makefile chessboard.cpp chesspiece.cpp -f u17173389Prac3Task1.tar.gz
